Repository TicketPing/TicketPing-Final, pull requests merged in 2024-12, with the labels that each got.

#58 [refactor #57] QueueCheckFilter 리팩토링
  common/caching/src/main/java/caching/config/RedisConfig.java
  common/caching/src/main/java/caching/repository/ReactiveRedisRepository.java
  common/caching/src/main/java/caching/repository/RedisRepository.java
  docker-compose/docker-compose.yml
  gateway/src/main/java/com/ticketPing/gateway/application/service/QueueCheckService.java
  gateway/src/main/java/com/ticketPing/gateway/common/dto/CustomErrorResponse.java
  gateway/src/main/java/com/ticketPing/gateway/common/exception/FilterErrorCase.java
  gateway/src/main/java/com/ticketPing/gateway/common/utils/ResponseWriter.java
  gateway/src/main/java/com/ticketPing/gateway/infrastructure/filter/APIType.java
  gateway/src/main/java/com/ticketPing/gateway/infrastructure/filter/QueueCheckFilter.java
Labels: refactor

#59 [feat #7] 로그아웃 코드 추가
  gateway/src/main/java/com/ticketPing/gateway/infrastructure/config/SecurityConfig.java
  gateway/src/main/java/com/ticketPing/gateway/infrastructure/filter/JwtFilter.java
  services/auth/src/main/java/com/ticketPing/auth/application/client/UserClient.java
  services/auth/src/main/java/com/ticketPing/auth/application/dto/LoginResponse.java
  services/auth/src/main/java/com/ticketPing/auth/application/dto/TokenResponse.java
  services/auth/src/main/java/com/ticketPing/auth/application/service/AuthService.java
  services/auth/src/main/java/com/ticketPing/auth/application/service/RefreshTokenCacheService.java
  services/auth/src/main/java/com/ticketPing/auth/application/service/TokenService.java
  services/auth/src/main/java/com/ticketPing/auth/common/constants/AuthConstants.java
  services/auth/src/main/java/com/ticketPing/auth/common/enums/Role.java
  services/auth/src/main/java/com/ticketPing/auth/infrastructure/client/UserFeignClient.java
  services/auth/src/main/java/com/ticketPing/auth/infrastructure/config/SwaggerConfig.java
  services/auth/src/main/java/com/ticketPing/auth/infrastructure/jwt/JwtTokenProvider.java
  services/auth/src/main/java/com/ticketPing/auth/presentation/controller/AuthController.java
  services/auth/src/main/resources/application.yml
Labels: feature

#60 [fix] Redis 키 만료 이벤트 수신 안되는 문제 해결
  common/caching/src/main/java/caching/config/RedisConfig.java
  gateway/src/main/java/com/ticketPing/gateway/infrastructure/filter/QueueCheckFilter.java
  services/order/src/main/java/com/ticketPing/order/infrastructure/config/RedisMessageListenerConfig.java
  services/queue-manage/src/main/java/com/ticketPing/queue_manage/QueueManageApplication.java
  services/queue-manage/src/main/java/com/ticketPing/queue_manage/infrastructure/config/RedisClusterProperties.java
  services/queue-manage/src/main/java/com/ticketPing/queue_manage/infrastructure/config/RedisMessageListenerConfig.java
  services/queue-manage/src/main/java/com/ticketPing/queue_manage/infrastructure/config/RedissonConfig.java
  services/queue-manage/src/main/java/com/ticketPing/queue_manage/infrastructure/config/RedissonMessageListenerConfig.java
  services/queue-manage/src/main/java/com/ticketPing/queue_manage/infrastructure/listener/RedissonExpirationListener.java
Labels: fix

#62 [refact #61] refresh token rotation 도입
  services/auth/src/main/java/com/ticketPing/auth/application/service/AuthService.java
  services/auth/src/main/java/com/ticketPing/auth/application/service/RefreshTokenCookieService.java
  services/auth/src/main/java/com/ticketPing/auth/common/constants/AuthConstants.java
  services/auth/src/main/java/com/ticketPing/auth/common/exception/AuthErrorCase.java
  services/auth/src/main/java/com/ticketPing/auth/infrastructure/http/HttpCookieManager.java
  services/auth/src/main/java/com/ticketPing/auth/infrastructure/jwt/JwtTokenProvider.java
  services/auth/src/main/java/com/ticketPing/auth/presentation/controller/AuthController.java
Labels: refactor

#63 [refactor] Redis 종속성 수정
  gateway/src/main/java/com/ticketPing/gateway/infrastructure/filter/QueueCheckFilter.java
  services/payment/Dockerfile
  services/queue-manage/build.gradle
  services/queue-manage/src/main/java/com/ticketPing/queue_manage/infrastructure/config/RedisClusterProperties.java
  services/queue-manage/src/main/java/com/ticketPing/queue_manage/infrastructure/config/RedissonConfig.java
Labels: refactor

#65 [refactor] user 서비스 리팩토링
  services/user/src/main/java/com/ticketPing/user/application/dto/UserResponse.java
  services/user/src/main/java/com/ticketPing/user/application/service/UserService.java
  services/user/src/main/java/com/ticketPing/user/domain/model/entity/User.java
  services/user/src/main/java/com/ticketPing/user/domain/model/enums/Gender.java
  services/user/src/main/java/com/ticketPing/user/domain/repository/UserRepository.java
  services/user/src/main/java/com/ticketPing/user/infrastructure/repository/UserJpaRepository.java
  services/user/src/test/java/com/ticketPing/user/CustomerApplicationTests.java
Labels: refactor

#67 [feat #66] 게이트웨이 라우터 서킷브레이커 설정
  gateway/build.gradle
  gateway/src/main/java/com/ticketPing/gateway/common/exception/CircuitBreakerErrorCase.java
  gateway/src/main/java/com/ticketPing/gateway/infrastructure/config/CircuitBreakerEventConfig.java
  gateway/src/main/java/com/ticketPing/gateway/infrastructure/config/RouteConfig.java
  gateway/src/main/java/com/ticketPing/gateway/presentation/controller/FallbackController.java
  gateway/src/main/resources/application.yml
Labels: feature

#69 [feat #68] 서킷브레이커 모니터링 설정
  monitoring/grafana/provisioning/alerting/alert-rule.yml
  monitoring/grafana/provisioning/dashboards/dashboards.yml
  monitoring/grafana/provisioning/dashboards/grafana-dashboard.json
  monitoring/grafana/provisioning/dashboards/spring-boot-dashboard.json
Labels: feature

#73 [fix] JwtFilter Preflight 요청 허용
  gateway/src/main/java/com/ticketPing/gateway/infrastructure/config/SecurityConfig.java
Labels: fix

#75 [fix] 요청 헤더 스펠링 변경
  gateway/src/main/java/com/ticketPing/gateway/infrastructure/config/RouteConfig.java
  gateway/src/main/resources/application.yml
  services/queue-manage/src/main/java/com/ticketPing/queue_manage/presentaion/controller/WaitingQueueController.java
  services/queue-manage/src/main/java/com/ticketPing/queue_manage/presentaion/controller/WorkingQueueController.java
Labels: fix

#77 [refact] 공연 더미 데이터 생성 시 좌석 정보 캐싱 추가
  services/performance/src/main/java/com/ticketPing/performance/domain/DataInitializer.java
Labels: refactor

#79 [fix @78] User, Auth 입력 값 검증 오류 해결
  services/auth/build.gradle
  services/auth/src/main/java/com/ticketPing/auth/presentation/request/LoginErrorMessage.java
  services/user/build.gradle
Labels: fix

#81 게이트웨이 CustomAuthenticationEntryPoint 구현
  gateway/src/main/java/com/ticketPing/gateway/common/exception/SecurityErrorCase.java
  gateway/src/main/java/com/ticketPing/gateway/infrastructure/config/CustomAuthenticationEntryPoint.java
  gateway/src/main/java/com/ticketPing/gateway/infrastructure/config/SecurityConfig.java
  gateway/src/main/java/com/ticketPing/gateway/infrastructure/filter/JwtFilter.java
  gateway/src/main/resources/application.yml
Labels: feature

#83 [refactor #82] 공연 서비스 ERD 수정
  common/dtos/src/main/java/performance/OrderInfoResponse.java
  services/order/src/main/java/com/ticketPing/order/application/dtos/OrderInfoResponse.java
  services/order/src/main/java/com/ticketPing/order/application/dtos/OrderResponse.java
  services/order/src/main/java/com/ticketPing/order/application/dtos/temp/SeatResponse.java
  services/order/src/main/java/com/ticketPing/order/application/enums/SeatStatus.java
  services/order/src/main/java/com/ticketPing/order/application/service/OrderService.java
  services/order/src/main/java/com/ticketPing/order/common/exception/OrderExceptionCase.java
  services/order/src/main/java/com/ticketPing/order/domain/model/entity/OrderSeat.java
  services/order/src/main/java/com/ticketPing/order/infrastructure/client/PerformanceClient.java
  services/order/src/main/java/com/ticketPing/order/infrastructure/listener/RedisKeyExpiredListener.java
  services/order/src/main/java/com/ticketPing/order/presentation/controller/OrderController.java
  services/order/src/main/resources/scripts/preReserve.lua
  services/performance/src/main/java/com/ticketPing/performance/application/dtos/OrderInfoResponse.java
  services/performance/src/main/java/com/ticketPing/performance/application/dtos/ScheduleResponse.java
  services/performance/src/main/java/com/ticketPing/performance/application/dtos/SeatResponse.java
  services/performance/src/main/java/com/ticketPing/performance/application/service/SeatService.java
  services/performance/src/main/java/com/ticketPing/performance/common/exception/SeatExceptionCase.java
  services/performance/src/main/java/com/ticketPing/performance/domain/DataInitializer.java
  services/performance/src/main/java/com/ticketPing/performance/domain/model/entity/Schedule.java
  services/performance/src/main/java/com/ticketPing/performance/domain/model/entity/Seat.java
  services/performance/src/main/java/com/ticketPing/performance/domain/model/enums/SeatStatus.java
  services/performance/src/main/java/com/ticketPing/performance/domain/repository/PerformanceRepository.java
Labels: refactor

#84 [fix] JwtFilter 로직 수정
  gateway/src/main/java/com/ticketPing/gateway/infrastructure/filter/JwtFilter.java
Labels: fix

#85 [feat] 주문, 결제 서비스 QueueCheckFilter 적용
  gateway/src/main/java/com/ticketPing/gateway/application/service/QueueCheckService.java
  gateway/src/main/java/com/ticketPing/gateway/common/utils/TokenValueGenerator.java
  gateway/src/main/java/com/ticketPing/gateway/infrastructure/config/RouteConfig.java
  services/queue-manage/src/main/java/com/ticketPing/queue_manage/presentaion/controller/WaitingQueueController.java
  services/queue-manage/src/main/java/com/ticketPing/queue_manage/presentaion/controller/WorkingQueueController.java
Labels: feature

#87 [feat #86] payment 서비스 PG사 연동 (TOSS)
  common/core/src/main/java/exception/ApplicationException.java
  common/core/src/main/java/exception/GlobalExceptionHandler.java
  common/dtos/src/main/java/order/OrderInfoForPaymentResponse.java
  common/messaging/src/main/java/messaging/events/PaymentCompletedEvent.java
  common/messaging/src/main/java/messaging/events/PaymentCreatedEvent.java
  common/messaging/src/main/java/messaging/topics/PaymentTopic.java
  docker-compose/docker-compose.yml
  gateway/src/main/java/com/ticketPing/gateway/infrastructure/config/RouteConfig.java
  gateway/src/main/java/com/ticketPing/gateway/infrastructure/filter/ApiType.java
  gateway/src/main/java/com/ticketPing/gateway/infrastructure/filter/QueueCheckFilter.java
  services/order/src/main/java/com/ticketPing/order/application/dtos/OrderInfoForPaymentResponse.java
  services/order/src/main/java/com/ticketPing/order/application/service/OrderService.java
  services/order/src/main/java/com/ticketPing/order/infrastructure/listener/EventConsumer.java
  services/order/src/main/java/com/ticketPing/order/presentation/controller/OrderController.java
  services/payment/build.gradle
  services/payment/src/main/java/com/ticketPing/payment/PaymentApplication.java
  services/payment/src/main/java/com/ticketPing/payment/application/client/OrderClient.java
  services/payment/src/main/java/com/ticketPing/payment/application/constants/TossPaymentConstants.java
  services/payment/src/main/java/com/ticketPing/payment/application/dto/PaymentResponse.java
  services/payment/src/main/java/com/ticketPing/payment/application/service/EventApplicationService.java
  services/payment/src/main/java/com/ticketPing/payment/application/service/PaymentApplicationService.java
  services/payment/src/main/java/com/ticketPing/payment/common/exception/PaymentErrorCase.java
  services/payment/src/main/java/com/ticketPing/payment/common/exception/PaymentException.java
  services/payment/src/main/java/com/ticketPing/payment/common/exception/PaymentExceptionHandler.java
  services/payment/src/main/java/com/ticketPing/payment/domain/model/entity/Payment.java
  services/payment/src/main/java/com/ticketPing/payment/domain/model/enums/PaymentStatus.java
  services/payment/src/main/java/com/ticketPing/payment/domain/service/PaymentDomainService.java
  services/payment/src/main/java/com/ticketPing/payment/infrastructure/client/OrderFeignClient.java
  services/payment/src/main/java/com/ticketPing/payment/infrastructure/config/KafkaTopicConfig.java
  services/payment/src/main/java/com/ticketPing/payment/infrastructure/config/RestTemplateConfig.java
  services/payment/src/main/java/com/ticketPing/payment/presentation/controller/PaymentController.java
  services/payment/src/main/java/com/ticketPing/payment/presentation/request/PaymentConfirmRequest.java
  services/payment/src/main/resources/application.yml
Labels: feature

#89 [refactor #88] 좌석 서비스 redis redisson 클라이언트로 변경
  services/performance/build.gradle
  services/performance/src/main/java/com/ticketPing/performance/PerformanceApplication.java
  services/performance/src/main/java/com/ticketPing/performance/application/dtos/SeatResponse.java
  services/performance/src/main/java/com/ticketPing/performance/application/service/SeatService.java
  services/performance/src/main/java/com/ticketPing/performance/domain/model/enums/SeatStatus.java
  services/performance/src/main/java/com/ticketPing/performance/infrastructure/config/RedissonConfig.java
Labels: refactor

#91 [feat #90] 공연 좌석 전체 캐싱 스케줄러 추가
  services/performance/src/main/java/com/ticketPing/performance/PerformanceApplication.java
  services/performance/src/main/java/com/ticketPing/performance/application/scheduler/SeatCacheScheduler.java
  services/performance/src/main/java/com/ticketPing/performance/application/service/PerformanceService.java
  services/performance/src/main/java/com/ticketPing/performance/application/service/ScheduleService.java
  services/performance/src/main/java/com/ticketPing/performance/application/service/SeatService.java
  services/performance/src/main/java/com/ticketPing/performance/common/exception/SeatExceptionCase.java
  services/performance/src/main/java/com/ticketPing/performance/domain/DataInitializer.java
  services/performance/src/main/java/com/ticketPing/performance/domain/repository/PerformanceRepository.java
  services/performance/src/main/java/com/ticketPing/performance/domain/repository/ScheduleRepository.java
  services/performance/src/main/java/com/ticketPing/performance/domain/repository/SeatRepository.java
  services/performance/src/main/java/com/ticketPing/performance/infrastructure/repository/PerformanceJpaRepository.java
  services/performance/src/main/java/com/ticketPing/performance/infrastructure/repository/SeatJpaRepository.java
  services/performance/src/main/java/com/ticketPing/performance/infrastructure/service/CacheService.java
  services/performance/src/main/java/com/ticketPing/performance/presentation/controller/PerformanceController.java
  services/performance/src/main/java/com/ticketPing/performance/presentation/controller/ScheduleController.java
  services/performance/src/main/java/com/ticketPing/performance/presentation/controller/SeatController.java
Labels: feature

#93 [refactor #92] 좌석 선점 API, 주문 생성 API 분리
  .gitignore
  common/core/src/main/java/response/CommonResponse.java
  common/dtos/src/main/java/performance/OrderSeatResponse.java
  common/dtos/src/main/java/performance/PaymentRequestDto.java
  common/dtos/src/main/java/performance/PaymentResponseDto.java
  services/order/src/main/java/com/ticketPing/order/application/client/PerformanceClient.java
  services/order/src/main/java/com/ticketPing/order/application/dtos/OrderResponse.java
  services/order/src/main/java/com/ticketPing/order/application/dtos/OrderSeatInfo.java
  services/order/src/main/java/com/ticketPing/order/application/service/OrderService.java
  services/order/src/main/java/com/ticketPing/order/common/exception/OrderExceptionCase.java
  services/order/src/main/java/com/ticketPing/order/domain/model/entity/Order.java
  services/order/src/main/java/com/ticketPing/order/domain/model/entity/OrderSeat.java
  services/order/src/main/java/com/ticketPing/order/infrastructure/client/PerformanceClient.java
  services/order/src/main/java/com/ticketPing/order/infrastructure/client/PerformanceFeignClient.java
  services/order/src/main/java/com/ticketPing/order/infrastructure/config/RedisLuaScriptConfig.java
  services/order/src/main/java/com/ticketPing/order/infrastructure/repository/OrderRepository.java
  services/order/src/main/java/com/ticketPing/order/infrastructure/service/RedisLuaService.java
  services/order/src/main/java/com/ticketPing/order/presentation/controller/OrderController.java
  services/order/src/main/java/com/ticketPing/order/presentation/request/OrderCreateDto.java
  services/order/src/main/resources/scripts/preReserve.lua
  services/performance/src/main/java/com/ticketPing/performance/application/dtos/OrderSeatResponse.java
  services/performance/src/main/java/com/ticketPing/performance/application/dtos/SeatResponse.java
  services/performance/src/main/java/com/ticketPing/performance/application/service/ScheduleService.java
  services/performance/src/main/java/com/ticketPing/performance/application/service/SeatService.java
  services/performance/src/main/java/com/ticketPing/performance/common/exception/ScheduleExceptionCase.java
  services/performance/src/main/java/com/ticketPing/performance/common/exception/SeatExceptionCase.java
  services/performance/src/main/java/com/ticketPing/performance/domain/DataInitializer.java
  services/performance/src/main/java/com/ticketPing/performance/domain/model/entity/SeatCache.java
  services/performance/src/main/java/com/ticketPing/performance/domain/repository/PerformanceRepository.java
  services/performance/src/main/java/com/ticketPing/performance/infrastructure/config/RedissonLuaScriptConfig.java
  services/performance/src/main/java/com/ticketPing/performance/infrastructure/service/CacheService.java
  services/performance/src/main/java/com/ticketPing/performance/infrastructure/service/LuaScriptService.java
  services/performance/src/main/java/com/ticketPing/performance/presentation/controller/SeatController.java
  services/performance/src/main/resources/application.yml
  services/performance/src/main/resources/scripts/preReserveScript.lua
  services/performance/src/test/java/com/ticketPing/performance/infrastructure/service/LuaScriptServiceTest.java
Labels: refactor

#95 [refactor #94] 좌석 선점 취소 API 추가
  services/performance/src/main/java/com/ticketPing/performance/application/service/SeatService.java
  services/performance/src/main/java/com/ticketPing/performance/domain/model/entity/SeatCache.java
  services/performance/src/main/java/com/ticketPing/performance/infrastructure/service/CacheService.java
  services/performance/src/main/java/com/ticketPing/performance/presentation/controller/SeatController.java
Labels: feature

#97 [refactor #96] 공연 단건 조회 반환값 수정
  services/performance/src/main/java/com/ticketPing/performance/application/dtos/PerformanceResponse.java
Labels: refactor

#99 [feat #98] 주문 검증 시 ttl 검증 및 연장 기능 추가
  services/order/src/main/java/com/ticketPing/order/application/client/PerformanceClient.java
  services/order/src/main/java/com/ticketPing/order/application/service/OrderService.java
  services/order/src/main/java/com/ticketPing/order/common/exception/OrderExceptionCase.java
  services/order/src/main/java/com/ticketPing/order/infrastructure/client/PerformanceFeignClient.java
  services/order/src/main/java/com/ticketPing/order/presentation/controller/OrderController.java
  services/performance/src/main/java/com/ticketPing/performance/application/service/SeatService.java
  services/performance/src/main/java/com/ticketPing/performance/common/constants/SeatConstants.java
  services/performance/src/main/java/com/ticketPing/performance/common/exception/SeatExceptionCase.java
  services/performance/src/main/java/com/ticketPing/performance/infrastructure/service/CacheService.java
  services/performance/src/main/java/com/ticketPing/performance/infrastructure/service/LuaScriptService.java
  services/performance/src/main/java/com/ticketPing/performance/presentation/controller/SeatClientController.java
  services/performance/src/main/java/com/ticketPing/performance/presentation/controller/SeatController.java
Labels: feature

#101 [feat #100] 게이트웨이 대기열 체크 필터에 좌석 선점 API, 주문 검증 API 추가
  gateway/src/main/java/com/ticketPing/gateway/infrastructure/config/RouteConfig.java
  gateway/src/main/java/com/ticketPing/gateway/infrastructure/filter/ApiType.java
  gateway/src/main/java/com/ticketPing/gateway/infrastructure/filter/QueueCheckFilter.java
Labels: feature

#105 [refactor #104] 자신의 주문 목록 조회 페이징 및 정리
  services/order/src/main/java/com/ticketPing/order/application/service/OrderService.java
  services/order/src/main/java/com/ticketPing/order/domain/repository/OrderRepository.java
  services/order/src/main/java/com/ticketPing/order/infrastructure/repository/OrderJpaRepository.java
  services/order/src/main/java/com/ticketPing/order/presentation/controller/OrderController.java
Labels: refactor
