Repository TicketPing/TicketPing-Final, pull requests merged in 2024-11, with the labels that each got.

#8 [fix #1] cpu 사용량 알람 수정
  monitoring/grafana/provisioning/alerting/alert-rule.yml
  monitoring/grafana/provisioning/datasources/datasources.yml
Labels: fix

#9 [feat#4] api-server 생성
  api-server/Dockerfile
  api-server/build.gradle
  api-server/src/main/java/com/ticketping/apiserver/ApiServerApplication.java
  api-server/src/main/resources/application.yml
  api-server/src/test/java/com/ticketping/apiserver/ApiServerApplicationTests.java
  build.gradle
  docker-compose-build.yml
  docker-compose.yml
  settings.gradle
Labels: feature

#11 [refactor] EventConsumer 코드 수정
  services/queue-manage/src/main/java/com/ticketPing/queue_manage/infrastructure/listener/EventConsumer.java
Labels: refactor

#12 [feat #3] redis cluster 적용하기
  .gitignore
  common/webflux/src/main/java/common/aop/LoggingAspect.java
  common/webflux/src/main/java/common/exception/GlobalExceptionHandler.java
  docker-compose-queue.yml
  docker-compose-redis.yml
  docker-compose.yml
  services/queue-manage/build.gradle
  services/queue-manage/src/gatling/java/simulation/WaitingQueueSimulation.java
  services/queue-manage/src/main/java/com/ticketPing/queue_manage/QueueManageApplication.java
  services/queue-manage/src/main/java/com/ticketPing/queue_manage/domain/command/waitingQueue/DeleteFirstWaitingQueueTokenCommand.java
  services/queue-manage/src/main/java/com/ticketPing/queue_manage/domain/command/workingQueue/DeleteWorkingQueueTokenCommand.java
  services/queue-manage/src/main/java/com/ticketPing/queue_manage/infrastructure/config/ReactiveKafkaConfig.java
  services/queue-manage/src/main/java/com/ticketPing/queue_manage/infrastructure/config/RedissonConfig.java
  services/queue-manage/src/main/java/com/ticketPing/queue_manage/infrastructure/enums/RedisClusterProperties.java
  services/queue-manage/src/main/java/com/ticketPing/queue_manage/infrastructure/enums/RedisKeyPrefix.java
  services/queue-manage/src/main/java/com/ticketPing/queue_manage/infrastructure/listener/EventConsumer.java
  services/queue-manage/src/main/resources/application-local.yaml
  services/queue-manage/src/main/resources/application.yml
Labels: feature

#19 [feat #14] 결제 완료 이벤트 구현
  common/messaging/src/main/java/events/PaymentCompletedEvent.java
  common/messaging/src/main/java/topics/PaymentTopic.java
  common/messaging/src/main/resources/application-kafka.yml
  services/order/src/main/java/com/ticketPing/order/infrastructure/listener/EventConsumer.java
  services/order/src/main/resources/application.yml
  services/payment/build.gradle
  services/payment/src/main/java/com/ticketPing/payment/application/service/PaymentService.java
  services/payment/src/main/java/com/ticketPing/payment/presentation/controller/PaymentController.java
  services/payment/src/main/resources/application-local.yml
  services/payment/src/main/resources/application.yml
Labels: feature

#20 [refactor #18] order 서비스 전체 코드 리팩토링
  services/order/build.gradle
  services/order/src/main/java/com/ticketPing/order/application/dtos/OrderInfoResponse.java
  services/order/src/main/java/com/ticketPing/order/application/dtos/OrderResponse.java
  services/order/src/main/java/com/ticketPing/order/application/dtos/OrderSeatInfo.java
  services/order/src/main/java/com/ticketPing/order/application/dtos/UserReservationDto.java
  services/order/src/main/java/com/ticketPing/order/application/dtos/temp/UserResponse.java
  services/order/src/main/java/com/ticketPing/order/application/service/OrderService.java
  services/order/src/main/java/com/ticketPing/order/domain/model/entity/Order.java
  services/order/src/main/java/com/ticketPing/order/domain/model/enums/OrderStatus.java
  services/order/src/main/java/com/ticketPing/order/exception/OrderExceptionCase.java
  services/order/src/main/java/com/ticketPing/order/infrastructure/client/PerformanceClient.java
  services/order/src/main/java/com/ticketPing/order/infrastructure/client/PerformanceService.java
  services/order/src/main/java/com/ticketPing/order/infrastructure/client/UserClient.java
  services/order/src/main/java/com/ticketPing/order/infrastructure/config/RedisConfig.java
  services/order/src/main/java/com/ticketPing/order/infrastructure/config/RedissonConfig.java
  services/order/src/main/java/com/ticketPing/order/infrastructure/listener/RedisKeyExpiredListener.java
  services/order/src/main/java/com/ticketPing/order/infrastructure/repository/OrderSeatRepository.java
  services/order/src/main/java/com/ticketPing/order/infrastructure/service/RedisService.java
  services/order/src/main/java/com/ticketPing/order/presentation/cases/exception/OrderExceptionCase.java
  services/order/src/main/java/com/ticketPing/order/presentation/cases/success/OrderSuccessCase.java
  services/order/src/main/java/com/ticketPing/order/presentation/controller/OrderController.java
  services/order/src/main/java/com/ticketPing/order/presentation/request/OrderCreateDto.java
  services/order/src/test/java/orderHttp/OrderHttp.http
Labels: refactor

#21 [feat #14] 결제 완료 이벤트 구현
  common/dtos/src/main/java/order/OrderInfoForPaymentResponse.java
  common/dtos/src/main/java/order/OrderInfoResponse.java
  common/messaging/src/main/java/events/OrderCompletedEvent.java
  docker-compose.yml
  services/order/src/main/java/com/ticketPing/order/application/dtos/OrderInfoForPaymentResponse.java
  services/order/src/main/java/com/ticketPing/order/application/dtos/OrderSeatInfo.java
  services/order/src/main/java/com/ticketPing/order/application/service/EventApplicationService.java
  services/order/src/main/java/com/ticketPing/order/application/service/OrderService.java
  services/order/src/main/java/com/ticketPing/order/domain/model/entity/Order.java
  services/order/src/main/java/com/ticketPing/order/infrastructure/listener/EventConsumer.java
  services/order/src/main/java/com/ticketPing/order/presentation/controller/OrderController.java
  services/payment/src/main/java/com/ticketPing/payment/application/dto/PaymentResponse.java
  services/payment/src/main/java/com/ticketPing/payment/application/service/EventApplicationService.java
  services/payment/src/main/java/com/ticketPing/payment/application/service/PaymentApplicationService.java
  services/payment/src/main/java/com/ticketPing/payment/application/service/PaymentService.java
  services/payment/src/main/java/com/ticketPing/payment/common/exception/PaymentErrorCase.java
  services/payment/src/main/java/com/ticketPing/payment/domain/model/entity/Payment.java
  services/payment/src/main/java/com/ticketPing/payment/domain/service/PaymentDomainService.java
  services/payment/src/main/java/com/ticketPing/payment/infrastructure/client/OrderClient.java
  services/payment/src/main/java/com/ticketPing/payment/infrastructure/config/SwaggerConfig.java
  services/payment/src/main/java/com/ticketPing/payment/presentation/controller/PaymentController.java
  services/queue-manage/src/gatling/java/simulation/WaitingQueueSimulation.java
  services/queue-manage/src/main/java/com/ticketPing/queue_manage/application/service/WaitingQueueService.java
  services/queue-manage/src/main/java/com/ticketPing/queue_manage/application/service/WorkingQueueService.java
  services/queue-manage/src/main/java/com/ticketPing/queue_manage/common/exception/QueueErrorCase.java
  services/queue-manage/src/main/java/com/ticketPing/queue_manage/infrastructure/config/RedisMessageListenerConfig.java
  services/queue-manage/src/main/java/com/ticketPing/queue_manage/infrastructure/enums/RedisClusterProperties.java
  services/queue-manage/src/main/java/com/ticketPing/queue_manage/infrastructure/listener/RedisExpirationListener.java
  services/queue-manage/src/main/java/com/ticketPing/queue_manage/infrastructure/repository/RedissonRepository.java
  services/queue-manage/src/main/java/com/ticketPing/queue_manage/infrastructure/repository/WorkingQueueRepositoryImpl.java
  services/queue-manage/src/main/java/com/ticketPing/queue_manage/presentaion/controller/WaitingQueueController.java
  services/queue-manage/src/main/java/com/ticketPing/queue_manage/presentaion/controller/WorkingQueueController.java
  services/queue-manage/src/main/resources/application-local.yaml
  services/queue-manage/src/main/resources/application.yml
Labels: feature

#25 [refactor #24] 좌석 선점 코드 루아 스크립트로 변경
  .gitignore
  services/order/src/main/java/com/ticketPing/order/application/service/OrderService.java
  services/order/src/main/java/com/ticketPing/order/exception/OrderExceptionCase.java
  services/order/src/main/java/com/ticketPing/order/infrastructure/config/RedisLuaScriptConfig.java
  services/order/src/main/java/com/ticketPing/order/infrastructure/listener/RedisKeyExpiredListener.java
  services/order/src/main/java/com/ticketPing/order/infrastructure/service/RedisLuaService.java
  services/order/src/main/java/com/ticketPing/order/presentation/controller/OrderController.java
  services/order/src/main/resources/scripts/preReserve.lua
  services/performance/src/main/java/com/ticketPing/performance/application/service/SeatService.java
Labels: refactor

#27 [refactor #26] docker compose 파일 수정, api 서버 삭제
  api-server/Dockerfile
  api-server/build.gradle
  api-server/src/main/java/com/ticketping/apiserver/ApiServerApplication.java
  api-server/src/main/resources/application.yml
  api-server/src/test/java/com/ticketping/apiserver/ApiServerApplicationTests.java
  build.gradle
  common/dtos/src/main/java/auth/LoginRequest.java
  common/dtos/src/main/java/auth/LoginResponse.java
  common/dtos/src/main/java/user/LoginRequest.java
  common/dtos/src/main/java/user/UserLookupRequest.java
  docker-compose-build.yml
  docker-compose-kafka.yml
  docker-compose-monitoring.yml
  docker-compose-postgres.yml
  docker-compose.yml
  settings.gradle
Labels: refactor

#31 [feat #30] github actions pull request 알람 파일 생성
  .github/workflows/pull_request_notification.yml
Labels: feature

#39 [feat #34] 공통 모듈 Monitoring 설정
  common/core/src/main/resources/application-eureka.yml
  common/monitoring/build.gradle
  common/monitoring/src/main/resources/application-monitoring.yml
  common/monitoring/src/main/resources/application.yml
  docker-compose-monitoring.yml
  gateway/build.gradle
  gateway/src/main/resources/application.yml
  gateway/src/main/resources/logback.xml
  monitoring/prometheus/prometheus.yml
  services/auth/build.gradle
  services/auth/src/main/resources/application.yml
  services/order/build.gradle
  services/order/src/main/resources/application.yml
  services/order/src/main/resources/logback.xml
  services/payment/build.gradle
  services/payment/src/main/resources/application.yml
  services/payment/src/main/resources/logback.xml
  services/performance/build.gradle
  services/performance/src/main/resources/application.yml
  services/performance/src/main/resources/logback.xml
  services/queue-manage/build.gradle
  services/queue-manage/src/main/resources/application.yml
  services/queue-manage/src/main/resources/logback.xml
  services/user/build.gradle
  services/user/src/main/resources/application.yml
  services/user/src/main/resources/logback.xml
  settings.gradle
Labels: feature

#41 [feat #40] 결제 생성 이벤트, EventLogger 구현
  common/messaging/src/main/java/messaging/events/PaymentCreatedEvent.java
  common/messaging/src/main/java/messaging/topics/PaymentTopic.java
  common/messaging/src/main/java/messaging/utils/EventLogger.java
  services/order/src/main/java/com/ticketPing/order/application/service/EventApplicationService.java
  services/order/src/main/java/com/ticketPing/order/application/service/OrderService.java
  services/order/src/main/java/com/ticketPing/order/infrastructure/listener/EventConsumer.java
  services/payment/src/main/java/com/ticketPing/payment/application/service/EventApplicationService.java
  services/payment/src/main/java/com/ticketPing/payment/application/service/PaymentApplicationService.java
  services/payment/src/main/java/com/ticketPing/payment/domain/model/entity/Payment.java
  services/queue-manage/src/main/java/com/ticketPing/queue_manage/infrastructure/listener/EventConsumer.java
Labels: feature

#43 [refactor] import 정리
  services/order/src/main/java/com/ticketPing/order/infrastructure/listener/EventConsumer.java
  services/payment/src/main/java/com/ticketPing/payment/application/service/EventApplicationService.java
  services/payment/src/main/java/com/ticketPing/payment/presentation/controller/PaymentController.java
Labels: refactor

#44 refresh 토큰 추가
  common/dtos/src/main/java/auth/LoginRequest.java
  common/dtos/src/main/java/auth/LoginResponse.java
  common/dtos/src/main/java/auth/UserCacheDto.java
  common/dtos/src/main/java/user/LoginRequest.java
  common/dtos/src/main/java/user/UserLookupRequest.java
  gateway/build.gradle
  gateway/src/main/java/com/ticketPing/gateway/application/dto/UserCache.java
  gateway/src/main/java/com/ticketPing/gateway/infrastructure/client/AuthClient.java
  gateway/src/main/java/com/ticketPing/gateway/infrastructure/security/JwtFilter.java
  gateway/src/main/resources/application.yml
  services/auth/build.gradle
  services/auth/src/main/java/com/ticketPing/auth/application/client/UserClient.java
  services/auth/src/main/java/com/ticketPing/auth/application/dto/LoginResponse.java
  services/auth/src/main/java/com/ticketPing/auth/application/service/AuthService.java
  services/auth/src/main/java/com/ticketPing/auth/application/service/TokenService.java
  services/auth/src/main/java/com/ticketPing/auth/application/service/enums/Role.java
  services/auth/src/main/java/com/ticketPing/auth/exception/AuthErrorCase.java
  services/auth/src/main/java/com/ticketPing/auth/exception/LoginErrorMessage.java
  services/auth/src/main/java/com/ticketPing/auth/infrastructure/client/UserFeignClient.java
  services/auth/src/main/java/com/ticketPing/auth/infrastructure/config/SwaggerConfig.java
  services/auth/src/main/java/com/ticketPing/auth/infrastructure/security/Role.java
  services/auth/src/main/java/com/ticketPing/auth/infrastructure/security/SecurityConfig.java
  services/auth/src/main/java/com/ticketPing/auth/presentation/cases/AuthErrorCase.java
  services/auth/src/main/java/com/ticketPing/auth/presentation/cases/AuthSuccessCase.java
  services/auth/src/main/java/com/ticketPing/auth/presentation/controller/AuthController.java
  services/auth/src/main/java/com/ticketPing/auth/presentation/request/LoginRequest.java
  services/auth/src/main/resources/application.yml
  services/user/src/main/java/com/ticketPing/user/application/service/UserService.java
  services/user/src/main/java/com/ticketPing/user/presentation/controller/UserController.java
  services/user/src/main/resources/application.yml
Labels: feature

#45 [refactor] 전체 리팩토링
  .dockerignore
  .gitignore
  common/caching/src/main/java/caching/enums/RedisKeyPrefix.java
  common/dtos/src/main/java/order/OrderInfoForPaymentResponse.java
  common/monitoring/build.gradle
  common/monitoring/src/main/resources/application-monitoring.yml
  docker-compose/docker-compose-build.yml
  docker-compose/docker-compose-kafka.yml
  docker-compose/docker-compose-monitoring.yml
  docker-compose/docker-compose-postgres.yml
  docker-compose/docker-compose-redis.yml
  docker-compose/docker-compose.yml
  docker-compose/end_service.sh
  docker-compose/start_service.sh
  services/auth/src/main/resources/logback.xml
  services/order/src/main/java/com/ticketPing/order/application/dtos/OrderInfoForPaymentResponse.java
  services/order/src/main/java/com/ticketPing/order/application/service/OrderService.java
  services/order/src/main/java/com/ticketPing/order/domain/model/entity/Order.java
  services/order/src/main/resources/logback.xml
  services/payment/src/main/resources/logback.xml
  services/performance/src/main/java/com/ticketPing/performance/application/service/SeatService.java
  services/performance/src/main/resources/logback.xml
  services/queue-manage/src/main/resources/logback.xml
  services/user/src/main/resources/logback.xml
Labels: refactor

#47 [refactor] 전체 코드 리팩토링
  common/core/src/main/java/cases/ErrorCase.java
  common/core/src/main/java/exception/ApplicationException.java
  common/core/src/main/java/exception/ErrorCase.java
  common/core/src/main/java/response/CommonResponse.java
  common/rdb/build.gradle
  common/rdb/src/main/java/audit/BaseEntity.java
  common/rdb/src/main/java/audit/JpaAuditingConfig.java
  common/rdb/src/main/resources/application-jpa.yml
  common/rdb/src/main/resources/application.yml
  services/auth/src/main/java/com/ticketPing/auth/application/service/AuthService.java
  services/auth/src/main/java/com/ticketPing/auth/application/service/TokenService.java
  services/auth/src/main/java/com/ticketPing/auth/application/service/enums/Role.java
  services/auth/src/main/java/com/ticketPing/auth/common/exception/AuthErrorCase.java
  services/auth/src/main/java/com/ticketPing/auth/exception/LoginErrorMessage.java
  services/auth/src/main/java/com/ticketPing/auth/presentation/controller/AuthController.java
  services/auth/src/main/java/com/ticketPing/auth/presentation/request/LoginErrorMessage.java
  services/auth/src/main/java/com/ticketPing/auth/presentation/request/LoginRequest.java
  services/order/build.gradle
  services/order/src/main/java/com/ticketPing/order/application/service/OrderService.java
  services/order/src/main/java/com/ticketPing/order/common/exception/OrderExceptionCase.java
  services/order/src/main/java/com/ticketPing/order/infrastructure/listener/RedisKeyExpiredListener.java
  services/order/src/main/java/com/ticketPing/order/infrastructure/service/RedisLuaService.java
  services/payment/build.gradle
  services/payment/src/main/java/com/ticketPing/payment/common/exception/PaymentErrorCase.java
  services/performance/build.gradle
  services/performance/src/main/java/com/ticketPing/performance/application/service/PerformanceService.java
  services/performance/src/main/java/com/ticketPing/performance/application/service/ScheduleService.java
  services/performance/src/main/java/com/ticketPing/performance/application/service/SeatService.java
  services/performance/src/main/java/com/ticketPing/performance/common/exception/PerformanceExceptionCase.java
  services/performance/src/main/java/com/ticketPing/performance/common/exception/ScheduleExceptionCase.java
  services/performance/src/main/java/com/ticketPing/performance/common/exception/SeatExceptionCase.java
  services/performance/src/main/java/com/ticketPing/performance/presentation/cases/success/PerformanceSuccessCase.java
  services/performance/src/main/java/com/ticketPing/performance/presentation/cases/success/ScheduleSuccessCase.java
  services/performance/src/main/java/com/ticketPing/performance/presentation/cases/success/SeatSuccessCase.java
  services/performance/src/main/java/com/ticketPing/performance/presentation/controller/PerformanceController.java
  services/performance/src/main/java/com/ticketPing/performance/presentation/controller/ScheduleController.java
  services/performance/src/main/java/com/ticketPing/performance/presentation/controller/SeatController.java
  services/queue-manage/src/main/java/com/ticketPing/queue_manage/common/exception/QueueErrorCase.java
  services/user/build.gradle
  services/user/src/main/java/com/ticketPing/user/application/service/UserService.java
  services/user/src/main/java/com/ticketPing/user/common/exception/UserErrorCase.java
  services/user/src/main/java/com/ticketPing/user/domain/entity/Gender.java
  services/user/src/main/java/com/ticketPing/user/infrastructure/config/SecurityConfig.java
  services/user/src/main/java/com/ticketPing/user/presentation/cases/UserErrorCase.java
  services/user/src/main/java/com/ticketPing/user/presentation/cases/UserInfoErrorMessage.java
  services/user/src/main/java/com/ticketPing/user/presentation/cases/UserSuccessCase.java
  services/user/src/main/java/com/ticketPing/user/presentation/controller/UserController.java
  services/user/src/main/java/com/ticketPing/user/presentation/request/CreateUserRequest.java
  services/user/src/main/java/com/ticketPing/user/presentation/request/UserInfoErrorMessage.java
  settings.gradle
Labels: refactor

#51 [feat #49] 공통 모듈 Kafka Cluster 적용
  common/messaging/src/main/java/messaging/config/KafkaConsumerConfig.java
  common/messaging/src/main/resources/application-kafka.yml
  docker-compose/docker-compose-kafka.yml
  services/queue-manage/src/main/java/com/ticketPing/queue_manage/infrastructure/config/ReactiveKafkaConfig.java
Labels: feature

#53 [fix #52] 게이트웨이 auth 통신 오류 수정
  gateway/build.gradle
  gateway/src/main/java/com/ticketPing/gateway/GatewayApplication.java
  gateway/src/main/java/com/ticketPing/gateway/application/client/AuthClient.java
  gateway/src/main/java/com/ticketPing/gateway/application/service/QueueCheckService.java
  gateway/src/main/java/com/ticketPing/gateway/common/dto/CustomErrorResponse.java
  gateway/src/main/java/com/ticketPing/gateway/common/exception/FilterErrorCase.java
  gateway/src/main/java/com/ticketPing/gateway/common/exception/SecurityErrorCase.java
  gateway/src/main/java/com/ticketPing/gateway/common/utils/ConfigHolder.java
  gateway/src/main/java/com/ticketPing/gateway/common/utils/QueueTokenValueGenerator.java
  gateway/src/main/java/com/ticketPing/gateway/common/utils/ResponseWriter.java
  gateway/src/main/java/com/ticketPing/gateway/dto/UserCache.java
  gateway/src/main/java/com/ticketPing/gateway/exception/SecurityErrorCase.java
  gateway/src/main/java/com/ticketPing/gateway/infrastructure/client/AuthWebClient.java
  gateway/src/main/java/com/ticketPing/gateway/infrastructure/config/RouteConfig.java
  gateway/src/main/java/com/ticketPing/gateway/infrastructure/config/SecurityConfig.java
  gateway/src/main/java/com/ticketPing/gateway/infrastructure/config/SwaggerConfig.java
  gateway/src/main/java/com/ticketPing/gateway/infrastructure/config/WebClientConfig.java
  gateway/src/main/java/com/ticketPing/gateway/infrastructure/filter/APIType.java
  gateway/src/main/java/com/ticketPing/gateway/infrastructure/filter/JwtFilter.java
  gateway/src/main/java/com/ticketPing/gateway/infrastructure/filter/QueueCheckFilter.java
  gateway/src/main/java/com/ticketPing/gateway/security/AuthClient.java
  gateway/src/main/java/com/ticketPing/gateway/security/JwtFilter.java
  services/auth/src/main/java/com/ticketPing/auth/presentation/controller/AuthController.java
Labels: fix

#55 [feat #54] 결제 단일 조회 API 구현
  common/dtos/src/main/java/payment/PaymentResponse.java
  gateway/src/main/java/com/ticketPing/gateway/infrastructure/filter/QueueCheckFilter.java
  services/payment/src/main/java/com/ticketPing/payment/application/dto/PaymentResponse.java
  services/payment/src/main/java/com/ticketPing/payment/application/service/PaymentApplicationService.java
  services/payment/src/main/java/com/ticketPing/payment/presentation/controller/PaymentController.java
Labels: feature

#56 [refactor] Kafka 클러스터 설정 수정
  common/messaging/src/main/resources/application-kafka.yml
  docker-compose/docker-compose-kafka.yml
  services/order/src/main/java/com/ticketPing/order/infrastructure/config/KafkaTopicConfig.java
  services/payment/src/main/java/com/ticketPing/payment/infrastructure/config/KafkaTopicConfig.java
Labels: refactor
