Repository TicketPing/TicketPing-Final, pull requests merged in 2025-01, with the labels that each got.

#107 [refactor #106] 자신의 주문 목록 확인에서 결제 대기 상태 제외
  services/order/src/main/java/com/ticketPing/order/application/service/OrderService.java
  services/order/src/main/java/com/ticketPing/order/domain/repository/OrderRepository.java
  services/order/src/main/java/com/ticketPing/order/infrastructure/repository/OrderJpaRepository.java
Labels: refactor

#109 [feat #108] 공연 10분 전 좌석 캐싱 스케줄러 실패 시 디스코드 알림 추가
  docker-compose/docker-compose.yml
  services/performance/src/main/java/com/ticketPing/performance/application/scheduler/SeatCacheScheduler.java
  services/performance/src/main/java/com/ticketPing/performance/application/service/PerformanceService.java
  services/performance/src/main/java/com/ticketPing/performance/common/exception/MessageExceptionCase.java
  services/performance/src/main/java/com/ticketPing/performance/domain/repository/PerformanceRepository.java
  services/performance/src/main/java/com/ticketPing/performance/infrastructure/config/RestTemplateConfig.java
  services/performance/src/main/java/com/ticketPing/performance/infrastructure/repository/PerformanceJpaRepository.java
  services/performance/src/main/java/com/ticketPing/performance/infrastructure/service/DiscordNotificationService.java
  services/performance/src/main/resources/application.yml
Labels: feature

#111 [feature #110] 모니터링 알람 추가
  monitoring/grafana/provisioning/alerting/alert-rule.yml
Labels: feature

#116 [refactor #115] 주문 생성 API 입력값 request body로 수정
  services/order/src/main/java/com/ticketPing/order/application/service/OrderService.java
  services/order/src/main/java/com/ticketPing/order/presentation/controller/OrderController.java
Labels: refactor

#117 [refactor #112] 좌석 선점 ttl 만료 이벤트 수정
  common/core/src/main/resources/application-eureka.yml
  common/messaging/src/main/java/messaging/events/OrderFailedEvent.java
  common/messaging/src/main/java/messaging/events/SeatPreReserveExpiredEvent.java
  common/messaging/src/main/java/messaging/topics/OrderTopic.java
  common/messaging/src/main/java/messaging/topics/SeatTopic.java
  services/order/build.gradle
  services/order/src/main/java/com/ticketPing/order/OrderApplication.java
  services/order/src/main/java/com/ticketPing/order/application/client/PaymentClient.java
  services/order/src/main/java/com/ticketPing/order/application/dtos/temp/SeatResponse.java
  services/order/src/main/java/com/ticketPing/order/application/enums/SeatStatus.java
  services/order/src/main/java/com/ticketPing/order/application/service/EventApplicationService.java
  services/order/src/main/java/com/ticketPing/order/application/service/OrderService.java
  services/order/src/main/java/com/ticketPing/order/domain/model/entity/Order.java
  services/order/src/main/java/com/ticketPing/order/domain/repository/OrderRepository.java
  services/order/src/main/java/com/ticketPing/order/infrastructure/client/PaymentFeignClient.java
  services/order/src/main/java/com/ticketPing/order/infrastructure/config/RedisMessageListenerConfig.java
  services/order/src/main/java/com/ticketPing/order/infrastructure/listener/EventConsumer.java
  services/order/src/main/java/com/ticketPing/order/infrastructure/listener/RedisKeyExpiredListener.java
  services/order/src/main/resources/application.yml
  services/payment/src/main/java/com/ticketPing/payment/application/service/PaymentApplicationService.java
  services/payment/src/main/java/com/ticketPing/payment/domain/repository/PaymentRepository.java
  services/payment/src/main/java/com/ticketPing/payment/domain/service/PaymentDomainService.java
  services/payment/src/main/java/com/ticketPing/payment/infrastructure/repository/PaymentJpaRepository.java
  services/payment/src/main/java/com/ticketPing/payment/infrastructure/repository/PaymentRepositoryImpl.java
  services/payment/src/main/java/com/ticketPing/payment/presentation/controller/PaymentController.java
  services/performance/src/main/java/com/ticketPing/performance/application/scheduler/SeatCacheScheduler.java
  services/performance/src/main/java/com/ticketPing/performance/application/service/EventApplicationService.java
  services/performance/src/main/java/com/ticketPing/performance/application/service/PerformanceService.java
  services/performance/src/main/java/com/ticketPing/performance/application/service/SeatService.java
  services/performance/src/main/java/com/ticketPing/performance/common/constants/SeatConstants.java
  services/performance/src/main/java/com/ticketPing/performance/domain/repository/PerformanceRepository.java
  services/performance/src/main/java/com/ticketPing/performance/infrastructure/config/KafkaTopicConfig.java
  services/performance/src/main/java/com/ticketPing/performance/infrastructure/config/RedissonMessageListenerConfig.java
  services/performance/src/main/java/com/ticketPing/performance/infrastructure/listener/EventConsumer.java
  services/performance/src/main/java/com/ticketPing/performance/infrastructure/listener/RedisKeyExpiredListener.java
  services/performance/src/main/java/com/ticketPing/performance/infrastructure/repository/CacheRepositoryImpl.java
  services/performance/src/main/java/com/ticketPing/performance/infrastructure/repository/PerformanceJpaRepository.java
  services/performance/src/main/java/com/ticketPing/performance/infrastructure/repository/SeatJpaRepository.java
  services/performance/src/main/java/com/ticketPing/performance/infrastructure/service/LuaScriptService.java
Labels: refactor

#119 [refactor #118] 서킷브레이커 TimeLimiter 설정 추가
  gateway/src/main/resources/application.yml
Labels: refactor

#121 [fix #120] 유레카 서버 설정 수정
  eureka-server/src/main/resources/application.yml
Labels: fix

#125 [fix #124] 좌석 선점 만료 이벤트 분산락 키 이름 수정
  services/performance/src/main/java/com/ticketPing/performance/common/constants/SeatConstants.java
  services/performance/src/main/java/com/ticketPing/performance/infrastructure/listener/RedisKeyExpiredListener.java
Labels: fix

#126 [feat] 공연 더미 데이터 추가
  services/performance/src/main/java/com/ticketPing/performance/domain/DataInitializer.java
Labels: feature

#127 [refactor] 메서드 이름 수정
  gateway/src/main/java/com/ticketPing/gateway/application/client/AuthClient.java
  gateway/src/main/java/com/ticketPing/gateway/infrastructure/filter/QueueCheckFilter.java
  services/auth/src/main/java/com/ticketPing/auth/infrastructure/service/RedisCacheService.java
  services/payment/src/main/java/com/ticketPing/payment/application/service/PaymentApplicationService.java
  services/payment/src/main/java/com/ticketPing/payment/domain/service/PaymentDomainService.java
  services/payment/src/main/java/com/ticketPing/payment/presentation/controller/PaymentController.java
  services/performance/src/main/java/com/ticketPing/performance/application/service/SeatService.java
  services/performance/src/main/java/com/ticketPing/performance/domain/repository/CacheRepository.java
  services/performance/src/main/java/com/ticketPing/performance/domain/repository/ScheduleRepository.java
  services/performance/src/main/java/com/ticketPing/performance/infrastructure/repository/CacheRepositoryImpl.java
Labels: refactor

#128 [refactor] TimeLimiter 시간 제한 10s -> 15s 수정
  gateway/src/main/resources/application.yml
Labels: refactor

#133 feignclinet, webclient에 retry 설정
  common/resilience4j/build.gradle
  common/resilience4j/src/main/java/resilience4j/config/CircuitBreakerEventConfig.java
  common/resilience4j/src/main/java/resilience4j/config/RetryEventConfig.java
  common/resilience4j/src/main/resources/application-circuit-breaker.yml
  gateway/src/main/java/com/ticketPing/gateway/infrastructure/client/AuthWebClient.java
  gateway/src/main/java/com/ticketPing/gateway/infrastructure/config/RetryEventConfig.java
  gateway/src/main/java/com/ticketPing/gateway/infrastructure/filter/JwtFilter.java
  gateway/src/main/resources/application.yml
  services/auth/build.gradle
  services/auth/src/main/java/com/ticketPing/auth/AuthApplication.java
  services/auth/src/main/java/com/ticketPing/auth/infrastructure/client/UserFeignClient.java
  services/auth/src/main/resources/application.yml
  services/order/build.gradle
  services/order/src/main/java/com/ticketPing/order/OrderApplication.java
  services/order/src/main/java/com/ticketPing/order/infrastructure/client/PaymentFeignClient.java
  services/order/src/main/java/com/ticketPing/order/infrastructure/client/PerformanceFeignClient.java
  services/order/src/main/java/com/ticketPing/order/presentation/controller/OrderController.java
  services/order/src/main/resources/application.yml
  settings.gradle
Labels: feature

#134 [feat #132] 작업열 토큰 TTL 연장 API 구현
  docker-compose/docker-compose.yml
  services/queue-manage/src/main/java/com/ticketPing/queue_manage/application/service/WorkingQueueService.java
  services/queue-manage/src/main/java/com/ticketPing/queue_manage/common/utils/ConfigHolder.java
  services/queue-manage/src/main/java/com/ticketPing/queue_manage/domain/command/waitingQueue/InsertWaitingQueueTokenCommand.java
  services/queue-manage/src/main/java/com/ticketPing/queue_manage/domain/command/workingQueue/ExtendWorkingQueueTokenTTLCommand.java
  services/queue-manage/src/main/java/com/ticketPing/queue_manage/domain/command/workingQueue/InsertWorkingQueueTokenCommand.java
  services/queue-manage/src/main/java/com/ticketPing/queue_manage/domain/repository/WorkingQueueRepository.java
  services/queue-manage/src/main/java/com/ticketPing/queue_manage/infrastructure/repository/WorkingQueueRepositoryImpl.java
  services/queue-manage/src/main/java/com/ticketPing/queue_manage/presentaion/controller/WorkingQueueController.java
  services/queue-manage/src/main/resources/application.yml
Labels: feature

#138 [fix] 안쓰는 api 삭제
  services/order/src/main/java/com/ticketPing/order/presentation/controller/OrderController.java
  services/user/src/main/java/com/ticketPing/user/application/service/UserService.java
  services/user/src/main/java/com/ticketPing/user/domain/repository/UserRepository.java
  services/user/src/main/java/com/ticketPing/user/presentation/controller/UserController.java
Labels: fix
